import '../../styles/globals.css'
import { Inter } from 'next/font/google'
import {Navbar} from "@/components";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next Page',
  description: 'Generated by create next main',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
